language: go
install:
- curl -LO https://github.com/gohugoio/hugo/releases/download/v0.69.0/hugo_0.69.0_Linux-64bit.deb
- sudo dpkg -i hugo_0.69.0_Linux-64bit.deb
- pip install --user awscli
-
- mkdir -p ~/.aws
- touch ~/.aws/credentials
- echo "[default"] >> ~/.aws/credentials
- echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
- echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
script:
- hugo version
- make deploy
branches:
  only:
  - master
notifications:
    email:
        on_failure: always